import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { useVehicles } from '@/hooks/useVehicles';
import { useAlertStats } from '@/hooks/useAlerts';
import { useGeofenceStats } from '@/hooks/useGeofences';
import { Truck, AlertCircle, MapPin } from 'lucide-react';
import { VehicleStatus } from '@/types/vehicle';
export default function DashboardPage() {
    const { data: vehiclesData, isLoading: vehiclesLoading } = useVehicles({ limit: 100 });
    const { data: alertStats, isLoading: alertsLoading } = useAlertStats();
    const { data: geofenceStats, isLoading: geofencesLoading } = useGeofenceStats();
    const vehicles = vehiclesData?.data || [];
    const activeVehicles = vehicles.filter((v) => v.status === VehicleStatus.ACTIVE).length;
    const offlineVehicles = vehicles.filter((v) => v.status === VehicleStatus.OFFLINE).length;
    const StatCard = ({ title, value, icon: Icon, subtitle, color = 'fleet-tracker', }) => (_jsx(Card, { children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: `rounded-lg bg-${color}-100 p-3`, children: _jsx(Icon, { className: `text-${color}-600`, size: 24 }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: title }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: value }), subtitle && _jsx("p", { className: "text-xs text-gray-500", children: subtitle })] })] }) }) }));
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: "Dashboard" }), _jsx("p", { className: "mt-2 text-gray-600", children: "Welcome back! Here's your fleet overview." })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: vehiclesLoading ? (_jsxs(_Fragment, { children: [_jsx(Skeleton, { className: "h-32" }), _jsx(Skeleton, { className: "h-32" }), _jsx(Skeleton, { className: "h-32" }), _jsx(Skeleton, { className: "h-32" })] })) : (_jsxs(_Fragment, { children: [_jsx(StatCard, { title: "Total Vehicles", value: vehicles.length, icon: Truck, subtitle: `${activeVehicles} active` }), _jsx(StatCard, { title: "Active Vehicles", value: activeVehicles, icon: Truck, subtitle: `${offlineVehicles} offline`, color: "green" }), _jsx(StatCard, { title: "Critical Alerts", value: alertsLoading ? '-' : alertStats?.critical || 0, icon: AlertCircle, color: "red" }), _jsx(StatCard, { title: "Geofences", value: geofencesLoading ? '-' : geofenceStats?.active || 0, icon: MapPin, subtitle: "Active", color: "blue" })] })) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-3", children: [_jsxs(Card, { className: "lg:col-span-2", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Fleet Status" }), _jsx(CardDescription, { children: "Your vehicles at a glance" })] }), _jsxs(CardContent, { children: [vehiclesLoading ? (_jsxs("div", { className: "space-y-3", children: [_jsx(Skeleton, { className: "h-12" }), _jsx(Skeleton, { className: "h-12" }), _jsx(Skeleton, { className: "h-12" })] })) : (_jsx("div", { className: "space-y-3", children: vehicles.slice(0, 5).map((vehicle) => (_jsxs("div", { className: "flex items-center justify-between rounded-lg border border-gray-200 p-4", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900", children: vehicle.name }), _jsx("p", { className: "text-sm text-gray-500", children: vehicle.registrationNumber })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "font-medium text-gray-900", children: [vehicle.speed.toFixed(0), " km/h"] }), _jsxs("p", { className: "text-xs text-gray-500", children: [vehicle.odometer.toLocaleString(), " km"] })] }), _jsx(Badge, { variant: vehicle.status === VehicleStatus.ACTIVE
                                                                ? 'default'
                                                                : vehicle.status === VehicleStatus.OFFLINE
                                                                    ? 'destructive'
                                                                    : 'secondary', children: vehicle.status })] })] }, vehicle.id))) })), _jsx(Button, { variant: "outline", className: "mt-4 w-full", children: "View All Vehicles" })] })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Alert Summary" }), _jsx(CardDescription, { children: "Unresolved alerts" })] }), _jsxs(CardContent, { children: [alertsLoading ? (_jsx(Skeleton, { className: "h-48" })) : (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Critical" }), _jsx("span", { className: "font-bold text-red-600", children: alertStats?.critical || 0 })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "High" }), _jsx("span", { className: "font-bold text-orange-600", children: alertStats?.high || 0 })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Medium" }), _jsx("span", { className: "font-bold text-yellow-600", children: alertStats?.medium || 0 })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Low" }), _jsx("span", { className: "font-bold text-blue-600", children: alertStats?.low || 0 })] }), _jsx("div", { className: "border-t border-gray-200 pt-4", children: _jsxs("div", { className: "flex items-center justify-between font-bold", children: [_jsx("span", { children: "Total" }), _jsx("span", { children: alertStats?.unacknowledged || 0 })] }) })] })), _jsx(Button, { variant: "outline", className: "mt-4 w-full", children: "View All Alerts" })] })] })] })] }));
}
//# sourceMappingURL=DashboardPage.js.map