import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { useUIStore } from '@/stores/uiStore';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { User, Bell, Palette } from 'lucide-react';
export default function SettingsPage() {
    const { user } = useAuth();
    const { theme, setTheme, locale, setLocale } = useUIStore();
    const [isEditing, setIsEditing] = useState(false);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: "Settings" }), _jsx("p", { className: "mt-2 text-gray-600", children: "Manage your profile and preferences" })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(User, { size: 20 }), "Profile"] }), _jsx(CardDescription, { children: "Manage your account information" })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "First Name" }), _jsx(Input, { type: "text", value: user?.firstName || '', disabled: !isEditing, className: "mt-1" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Last Name" }), _jsx(Input, { type: "text", value: user?.lastName || '', disabled: !isEditing, className: "mt-1" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Email" }), _jsx(Input, { type: "email", value: user?.email || '', disabled: true, className: "mt-1" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Role" }), _jsx(Input, { type: "text", value: user?.role || '', disabled: true, className: "mt-1" })] }), _jsx(Button, { onClick: () => setIsEditing(!isEditing), className: "w-full", variant: isEditing ? 'default' : 'outline', children: isEditing ? 'Save Changes' : 'Edit Profile' })] })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Palette, { size: 20 }), "Preferences"] }), _jsx(CardDescription, { children: "Customize your experience" })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-3", children: "Theme" }), _jsx("div", { className: "flex gap-4", children: ['light', 'dark'].map((t) => (_jsx("button", { onClick: () => setTheme(t), className: `rounded-lg px-4 py-2 font-medium transition-colors ${theme === t
                                                ? 'bg-fleet-tracker-600 text-white'
                                                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`, children: t.charAt(0).toUpperCase() + t.slice(1) }, t))) })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-3", children: "Language" }), _jsxs("select", { value: locale, onChange: (e) => setLocale(e.target.value), className: "rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50", children: [_jsx("option", { value: "en", children: "English" }), _jsx("option", { value: "es", children: "Espa\u00F1ol" }), _jsx("option", { value: "fr", children: "Fran\u00E7ais" }), _jsx("option", { value: "de", children: "Deutsch" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-3", children: "Speed Unit" }), _jsxs("select", { className: "rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50", children: [_jsx("option", { value: "kmh", children: "Kilometers per hour (km/h)" }), _jsx("option", { value: "mph", children: "Miles per hour (mph)" }), _jsx("option", { value: "kn", children: "Knots (kn)" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-3", children: "Distance Unit" }), _jsxs("select", { className: "rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50", children: [_jsx("option", { value: "km", children: "Kilometers (km)" }), _jsx("option", { value: "mi", children: "Miles (mi)" })] })] })] })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Bell, { size: 20 }), "Notifications"] }), _jsx(CardDescription, { children: "Control how you receive alerts" })] }), _jsxs(CardContent, { className: "space-y-4", children: [[
                                { label: 'Email Notifications', key: 'email' },
                                { label: 'Push Notifications', key: 'push' },
                                { label: 'SMS Notifications', key: 'sms' },
                            ].map((item) => (_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("label", { className: "text-sm font-medium text-gray-700", children: item.label }), _jsx("input", { type: "checkbox", defaultChecked: true, className: "h-4 w-4" })] }, item.key))), _jsx(Button, { className: "w-full mt-4", children: "Save Preferences" })] })] }), _jsxs(Card, { className: "border-red-200", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-red-600", children: "Danger Zone" }) }), _jsxs(CardContent, { className: "space-y-4", children: [_jsx("p", { className: "text-sm text-gray-600", children: "Once you delete your account, there is no going back. Please be certain." }), _jsx(Button, { variant: "destructive", className: "w-full", children: "Delete Account" })] })] })] }));
}
//# sourceMappingURL=SettingsPage.js.map